version: '3'
services:

  ### Kafka Single Node Cluster ###
  kafka:
    image: wurstmeister/kafka
    container_name: kiro-kafka
    networks:
      - kiro
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "items:1:1:compact,offers:1:1:compact,terms:1:1:compact,titles:1:1:compact"
    depends_on:
      - zookeeper

  ### Zookeeper for Kafka ###
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: kiro-zk
    networks:
      - kiro
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  ### Couchbase Database Server ###
  couchbase-server:
    image: couchbase
    container_name: kiro-couch
    networks:
      - kiro
    ports:
    - "8091-8094:8091-8094"
    - "11210:11210"
  ### The network that allows the above services to communicate ###
networks:
  kiro:
    driver: bridge