spring:
  application:
    name: title-discovery-api

couchbase.cluster:
  host: localhost:8091
  title-bucket: tds-data
  username: tds-full
  password: tds-full

kafka:
  bootstrap-servers: 127.0.0.1:9092
  application.id: title-discovery
  topic:
    item: items
    offer: offers
    term: terms
    title: titles

server:
  port: 8080
  maxHttpHeaderSize: 131072

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /