apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: td
  labels:
    name: kafka
spec:
  ports:
    - name: kafka-port
      port: 9092
      protocol: TCP
      nodePort: 30038
  selector:
    name: kafka
  type: NodePort

---

